ldapPasswordReset-main:
    path:	/
    defaults:	{ _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::main' }
ldapPasswordReset-enterEmail:
    path:	/enterEmail
    defaults:	{ _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::enterEmail' }
ldapPasswordReset-resetPassword:
    path:	/resetPassword
    defaults:	{ _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::resetPassword' }
ldapPasswordReset-validateMagicLink:
    path:	/validateMagicLink
    defaults:	{ _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::validateMagicLink' }
ldapPasswordReset-invalidMagicLink:
    path:	/invalidMagicLink
    defaults:	{ _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::invalidMagicLink' }
